CREATE TABLE IF NOT EXISTS `activities` (
  `id` VARCHAR(36) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `activity_type` ENUM('task', 'event', 'phone_call', 'meeting') NOT NULL DEFAULT 'task',
  `status` ENUM('not_started', 'in_progress', 'completed', 'cancelled') NOT NULL DEFAULT 'not_started',
  `priority` ENUM('low', 'medium', 'high') NOT NULL DEFAULT 'medium',
  `assigned_to` VARCHAR(36) DEFAULT NULL,
  `start_date` DATETIME DEFAULT NULL,
  `end_date` DATETIME DEFAULT NULL,
  `due_date` DATETIME DEFAULT NULL,
  `customer_id` VARCHAR(36) DEFAULT NULL,
  `vendor_id` VARCHAR(36) DEFAULT NULL,
  `description` TEXT DEFAULT NULL,
  `created_by` VARCHAR(36) DEFAULT NULL,
  `is_deleted` TINYINT(1) DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_activities_assigned_to` (`assigned_to`),
  KEY `idx_activities_customer_id` (`customer_id`),
  KEY `idx_activities_vendor_id` (`vendor_id`),
  KEY `idx_activities_is_deleted` (`is_deleted`),
  CONSTRAINT `fk_activities_assigned_to` FOREIGN KEY (`assigned_to`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_activities_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_activities_vendor_id` FOREIGN KEY (`vendor_id`) REFERENCES `vendors` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_activities_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
